uisp:
  # x-auth-token:  # DON'T FILL ME IN (SECURITY RISK) POPULATE THIS PARAMETER VIA THE .env FILE
  hostname: uisp.mesh.nycmesh.net
  scheme: https
  skip-verify-tls: true # true needed for self-signed certs
  debug: true
